### ISSUE TITLE
exception with

### ISSUE THREAD

**Issue by dufoli** [quarkusio/gizmo#64]
[error]: Build step io.quarkiverse.cxf.deployment.QuarkusCxfProcessor#build threw an exception: java.lang.IllegalArgumentException: Unsupported api 589824
        at org.objectweb.asm.ClassVisitor.<init>(ClassVisitor.java:76)
        at io.quarkus.gizmo.GizmoClassVisitor.<init>(GizmoClassVisitor.java:22)
when  I use
final GizmoClassVisitor cw = new GizmoClassVisitor(Gizmo.ASM_API_VERSION, file,
                classOutput.getSourceWriter(postFixedName));

java 8 version seems to be 589824.
I do not understand why Gizmo produce a such error.

**Comment by gwenneg** [comment]
This can happen when several versions of asm are present in the classpath. See https://github.com/quarkusio/quarkus/issues/9832 for more details about it.

**Comment by dufoli** [comment]
I have check dependency tree and not sure that we have it here:
[INFO] org.acme:cxf-test:jar:1.0.0-SNAPSHOT
[INFO] +- io.quarkus:quarkus-resteasy:jar:1.9.2.Final:compile
[INFO] |  +- io.quarkus:quarkus-vertx-http:jar:1.9.2.Final:compile
[INFO] |  |  +- io.quarkus:quarkus-security-runtime-spi:jar:1.9.2.Final:compile
[INFO] |  |  +- io.quarkus:quarkus-development-mode-spi:jar:1.9.2.Final:compile
[INFO] |  |  +- io.quarkus.security:quarkus-security:jar:1.1.3.Final:compile
[INFO] |  |  |  \- io.smallrye.reactive:mutiny:jar:0.9.0:compile
[INFO] |  |  |     \- org.reactivestreams:reactive-streams:jar:1.0.3:compile
[INFO] |  |  +- io.quarkus:quarkus-vertx-core:jar:1.9.2.Final:compile
[INFO] |  |  |  +- io.quarkus:quarkus-netty:jar:1.9.2.Final:compile
[INFO] |  |  |  |  +- io.netty:netty-codec:jar:4.1.49.Final:compile
[INFO] |  |  |  |  \- io.netty:netty-handler:jar:4.1.49.Final:compile
[INFO] |  |  |  \- io.vertx:vertx-core:jar:3.9.4:compile
[INFO] |  |  |     +- io.netty:netty-common:jar:4.1.49.Final:compile
[INFO] |  |  |     +- io.netty:netty-buffer:jar:4.1.49.Final:compile
[INFO] |  |  |     +- io.netty:netty-transport:jar:4.1.49.Final:compile
[INFO] |  |  |     +- io.netty:netty-handler-proxy:jar:4.1.49.Final:compile
[INFO] |  |  |     |  \- io.netty:netty-codec-socks:jar:4.1.49.Final:compile
[INFO] |  |  |     +- io.netty:netty-codec-http2:jar:4.1.49.Final:compile
[INFO] |  |  |     +- io.netty:netty-resolver:jar:4.1.49.Final:compile
[INFO] |  |  |     \- io.netty:netty-resolver-dns:jar:4.1.49.Final:compile
[INFO] |  |  |        \- io.netty:netty-codec-dns:jar:4.1.49.Final:compile
[INFO] |  |  \- io.vertx:vertx-web:jar:3.9.4:compile
[INFO] |  |     +- io.vertx:vertx-web-common:jar:3.9.4:compile
[INFO] |  |     +- io.vertx:vertx-auth-common:jar:3.9.4:compile
[INFO] |  |     \- io.vertx:vertx-bridge-common:jar:3.9.4:compile
[INFO] |  \- io.quarkus:quarkus-resteasy-server-common:jar:1.9.2.Final:compile
[INFO] |     +- io.quarkus:quarkus-resteasy-common:jar:1.9.2.Final:compile
[INFO] |     |  \- org.jboss.resteasy:resteasy-core:jar:4.5.8.Final:compile
[INFO] |     |     +- org.jboss.spec.javax.ws.rs:jboss-jaxrs-api_2.1_spec:jar:2.0.1.Final:compile
[INFO] |     |     +- org.jboss.resteasy:resteasy-core-spi:jar:4.5.8.Final:compile
[INFO] |     |     \- com.ibm.async:asyncutil:jar:0.1.0:compile
[INFO] |     \- jakarta.validation:jakarta.validation-api:jar:2.0.2:compile
[INFO] +- io.quarkus:quarkus-arc:jar:1.9.2.Final:compile
[INFO] |  +- io.quarkus.arc:arc:jar:1.9.2.Final:compile
[INFO] |  |  +- jakarta.enterprise:jakarta.enterprise.cdi-api:jar:2.0.2:compile
[INFO] |  |  |  +- jakarta.el:jakarta.el-api:jar:3.0.3:compile
[INFO] |  |  |  \- jakarta.interceptor:jakarta.interceptor-api:jar:1.2.5:compile
[INFO] |  |  |     \- jakarta.ejb:jakarta.ejb-api:jar:3.2.6:compile
[INFO] |  |  +- jakarta.annotation:jakarta.annotation-api:jar:1.3.5:compile
[INFO] |  |  +- jakarta.transaction:jakarta.transaction-api:jar:1.3.3:compile
[INFO] |  |  \- org.jboss.logging:jboss-logging:jar:3.4.1.Final:compile
[INFO] |  +- io.quarkus:quarkus-core:jar:1.9.2.Final:compile
[INFO] |  |  +- jakarta.inject:jakarta.inject-api:jar:1.0:compile
[INFO] |  |  +- io.quarkus:quarkus-ide-launcher:jar:1.9.2.Final:compile
[INFO] |  |  +- io.smallrye.config:smallrye-config:jar:1.9.3:compile
[INFO] |  |  |  +- io.smallrye.common:smallrye-common-annotation:jar:1.4.0:compile
[INFO] |  |  |  +- io.smallrye.config:smallrye-config-common:jar:1.9.3:compile
[INFO] |  |  |  +- io.smallrye.common:smallrye-common-expression:jar:1.4.0:compile
[INFO] |  |  |  |  \- io.smallrye.common:smallrye-common-function:jar:1.4.0:compile
[INFO] |  |  |  +- io.smallrye.common:smallrye-common-constraint:jar:1.4.0:compile
[INFO] |  |  |  \- io.smallrye.common:smallrye-common-classloader:jar:1.4.0:compile
[INFO] |  |  +- org.jboss.logmanager:jboss-logmanager-embedded:jar:1.0.6:compile
[INFO] |  |  +- org.jboss.logging:jboss-logging-annotations:jar:2.1.0.Final:compile
[INFO] |  |  +- org.jboss.threads:jboss-threads:jar:3.1.1.Final:compile
[INFO] |  |  +- org.slf4j:slf4j-api:jar:1.7.30:compile
[INFO] |  |  +- org.jboss.slf4j:slf4j-jboss-logging:jar:1.2.0.Final:compile
[INFO] |  |  +- org.graalvm.sdk:graal-sdk:jar:20.2.0:compile
[INFO] |  |  +- org.wildfly.common:wildfly-common:jar:1.5.4.Final-format-001:compile
[INFO] |  |  \- io.quarkus:quarkus-bootstrap-runner:jar:1.9.2.Final:compile
[INFO] |  \- org.eclipse.microprofile.context-propagation:microprofile-context-propagation-api:jar:1.0.1:compile
[INFO] +- io.quarkiverse.cxf:quarkus-cxf:jar:0.1.2-SNAPSHOT:compile
[INFO] |  +- org.apache.cxf:cxf-rt-frontend-jaxws:jar:3.4.1:compile
[INFO] |  |  +- xml-resolver:xml-resolver:jar:1.2:compile
[INFO] |  |  +- org.ow2.asm:asm:jar:8.0.1:compile
[INFO] |  |  +- org.apache.cxf:cxf-core:jar:3.4.1:compile
[INFO] |  |  |  +- com.fasterxml.woodstox:woodstox-core:jar:6.1.1:compile
[INFO] |  |  |  |  \- org.codehaus.woodstox:stax2-api:jar:4.2:compile
[INFO] |  |  |  \- org.apache.ws.xmlschema:xmlschema-core:jar:2.2.5:compile
[INFO] |  |  +- org.apache.cxf:cxf-rt-bindings-soap:jar:3.4.1:compile
[INFO] |  |  |  +- org.apache.cxf:cxf-rt-wsdl:jar:3.4.1:compile
[INFO] |  |  |  |  \- wsdl4j:wsdl4j:jar:1.6.3:compile
[INFO] |  |  |  \- org.apache.cxf:cxf-rt-databinding-jaxb:jar:3.4.1:compile
[INFO] |  |  +- org.apache.cxf:cxf-rt-bindings-xml:jar:3.4.1:compile
[INFO] |  |  +- org.apache.cxf:cxf-rt-frontend-simple:jar:3.4.1:compile
[INFO] |  |  +- org.apache.cxf:cxf-rt-ws-addr:jar:3.4.1:compile
[INFO] |  |  |  \- org.apache.cxf:cxf-rt-ws-policy:jar:3.4.1:compile
[INFO] |  |  |     \- org.apache.neethi:neethi:jar:3.1.1:compile
[INFO] |  |  +- jakarta.xml.ws:jakarta.xml.ws-api:jar:2.3.3:compile
[INFO] |  |  +- jakarta.jws:jakarta.jws-api:jar:2.1.0:compile
[INFO] |  |  +- jakarta.xml.soap:jakarta.xml.soap-api:jar:1.4.2:compile
[INFO] |  |  |  \- jakarta.activation:jakarta.activation-api:jar:1.2.1:compile
[INFO] |  |  +- com.sun.activation:jakarta.activation:jar:1.2.1:compile
[INFO] |  |  +- com.sun.xml.messaging.saaj:saaj-impl:jar:1.5.2:runtime
[INFO] |  |  |  \- org.jvnet.staxex:stax-ex:jar:1.8.3:runtime
[INFO] |  |  +- org.apache.geronimo.specs:geronimo-jta_1.1_spec:jar:1.1.1:compile
[INFO] |  |  \- org.jboss.spec.javax.rmi:jboss-rmi-api_1.0_spec:jar:1.0.6.Final:compile
[INFO] |  +- jakarta.servlet:jakarta.servlet-api:jar:4.0.3:compile
[INFO] |  +- org.apache.cxf:cxf-rt-transports-http:jar:3.4.1:compile
[INFO] |  +- io.quarkus:quarkus-jaxb:jar:1.9.2.Final:compile
[INFO] |  +- io.quarkus:quarkus-jaxp:jar:1.9.2.Final:compile
[INFO] |  +- io.quarkus:quarkus-jackson:jar:1.9.2.Final:compile
[INFO] |  |  +- com.fasterxml.jackson.core:jackson-databind:jar:2.11.3:compile
[INFO] |  |  |  +- com.fasterxml.jackson.core:jackson-annotations:jar:2.11.3:compile
[INFO] |  |  |  \- com.fasterxml.jackson.core:jackson-core:jar:2.11.3:compile
[INFO] |  |  +- com.fasterxml.jackson.datatype:jackson-datatype-jsr310:jar:2.11.3:compile
[INFO] |  |  +- com.fasterxml.jackson.datatype:jackson-datatype-jdk8:jar:2.11.3:compile
[INFO] |  |  \- com.fasterxml.jackson.module:jackson-module-parameter-names:jar:2.11.3:compile
[INFO] |  +- io.quarkus:quarkus-undertow:jar:1.9.2.Final:compile
[INFO] |  |  +- io.quarkus.http:quarkus-http-servlet:jar:3.0.15.Final:compile
[INFO] |  |  +- io.quarkus.http:quarkus-http-vertx-backend:jar:3.0.15.Final:compile
[INFO] |  |  |  \- io.quarkus.http:quarkus-http-http-core:jar:3.0.15.Final:compile
[INFO] |  |  \- io.quarkus.http:quarkus-http-core:jar:3.0.15.Final:compile
[INFO] |  |     \- io.netty:netty-codec-http:jar:4.1.49.Final:compile
[INFO] |  +- org.jboss.spec.javax.xml.bind:jboss-jaxb-api_2.3_spec:jar:2.0.0.Final:compile
[INFO] |  \- org.glassfish.jaxb:jaxb-runtime:jar:2.3.3-b02:compile
[INFO] |     +- org.glassfish.jaxb:txw2:jar:2.3.3-b02:compile
[INFO] |     \- com.sun.istack:istack-commons-runtime:jar:3.0.10:compile
[INFO] +- org.apache.camel.quarkus:camel-quarkus-timer:jar:1.3.0:compile
[INFO] |  +- org.apache.camel.quarkus:camel-quarkus-core:jar:1.3.0:compile
[INFO] |  |  +- org.apache.camel.quarkus:camel-quarkus-support-common:jar:1.3.0:compile
[INFO] |  |  +- org.apache.camel:camel-core-engine:jar:3.6.0:compile
[INFO] |  |  |  +- org.apache.camel:camel-api:jar:3.6.0:compile
[INFO] |  |  |  +- org.apache.camel:camel-management-api:jar:3.6.0:compile
[INFO] |  |  |  \- org.apache.camel:camel-util:jar:3.6.0:compile
[INFO] |  |  +- org.apache.camel:camel-base:jar:3.6.0:compile
[INFO] |  |  +- org.apache.camel:camel-core-languages:jar:3.6.0:compile
[INFO] |  |  +- org.apache.camel:camel-endpointdsl:jar:3.6.0:compile
[INFO] |  |  +- org.apache.camel:camel-componentdsl:jar:3.6.0:compile
[INFO] |  |  +- org.apache.camel:camel-core-catalog:jar:3.6.0:compile
[INFO] |  |  |  \- org.apache.camel:camel-tooling-model:jar:3.6.0:compile
[INFO] |  |  |     \- org.apache.camel:camel-util-json:jar:3.6.0:compile
[INFO] |  |  \- org.apache.camel:camel-microprofile-config:jar:3.6.0:compile
[INFO] |  |     \- org.eclipse.microprofile.config:microprofile-config-api:jar:1.4:compile
[INFO] |  \- org.apache.camel:camel-timer:jar:3.6.0:compile
[INFO] |     \- org.apache.camel:camel-support:jar:3.6.0:compile
[INFO] +- org.apache.camel.quarkus:camel-quarkus-log:jar:1.3.0:compile
[INFO] |  \- org.apache.camel:camel-log:jar:3.6.0:compile
[INFO] +- io.quarkus:quarkus-junit5:jar:1.9.2.Final:test
[INFO] |  +- io.quarkus:quarkus-bootstrap-core:jar:1.9.2.Final:test
[INFO] |  |  +- io.quarkus:quarkus-bootstrap-app-model:jar:1.9.2.Final:test
[INFO] |  |  +- io.quarkus:quarkus-bootstrap-maven-resolver:jar:1.9.2.Final:test
[INFO] |  |  |  +- org.apache.maven:maven-embedder:jar:3.6.3:test
[INFO] |  |  |  |  +- org.apache.maven:maven-settings:jar:3.6.3:test
[INFO] |  |  |  |  +- org.apache.maven:maven-core:jar:3.6.3:test
[INFO] |  |  |  |  |  +- org.apache.maven:maven-artifact:jar:3.6.3:test
[INFO] |  |  |  |  |  \- org.codehaus.plexus:plexus-component-annotations:jar:2.1.0:test
[INFO] |  |  |  |  +- org.apache.maven:maven-plugin-api:jar:3.6.3:test
[INFO] |  |  |  |  +- org.apache.maven:maven-model:jar:3.6.3:test
[INFO] |  |  |  |  +- org.apache.maven:maven-model-builder:jar:3.6.3:test
[INFO] |  |  |  |  +- org.apache.maven:maven-builder-support:jar:3.6.3:test
[INFO] |  |  |  |  +- org.apache.maven.resolver:maven-resolver-api:jar:1.4.1:test
[INFO] |  |  |  |  +- org.apache.maven.resolver:maven-resolver-util:jar:1.4.1:test
[INFO] |  |  |  |  +- org.apache.maven.shared:maven-shared-utils:jar:3.2.1:test
[INFO] |  |  |  |  |  \- commons-io:commons-io:jar:2.8.0:test
[INFO] |  |  |  |  +- com.google.inject:guice:jar:no_aop:4.2.1:test
[INFO] |  |  |  |  |  \- com.google.guava:guava:jar:29.0-jre:test
[INFO] |  |  |  |  |     +- com.google.guava:failureaccess:jar:1.0.1:test
[INFO] |  |  |  |  |     \- com.google.guava:listenablefuture:jar:9999.0-empty-to-avoid-conflict-with-guava:test
[INFO] |  |  |  |  +- org.codehaus.plexus:plexus-utils:jar:3.2.1:test
[INFO] |  |  |  |  +- org.codehaus.plexus:plexus-classworlds:jar:2.5.2:test
[INFO] |  |  |  |  \- commons-cli:commons-cli:jar:1.4:test
[INFO] |  |  |  +- org.eclipse.sisu:org.eclipse.sisu.plexus:jar:0.3.4:test
[INFO] |  |  |  +- org.apache.maven:maven-settings-builder:jar:3.6.3:test
[INFO] |  |  |  |  +- org.codehaus.plexus:plexus-interpolation:jar:1.25:test
[INFO] |  |  |  |  \- org.sonatype.plexus:plexus-sec-dispatcher:jar:1.4:test
[INFO] |  |  |  |     \- org.sonatype.plexus:plexus-cipher:jar:1.4:test
[INFO] |  |  |  +- org.apache.maven:maven-resolver-provider:jar:3.6.3:test
[INFO] |  |  |  |  +- org.apache.maven:maven-repository-metadata:jar:3.6.3:test
[INFO] |  |  |  |  +- org.apache.maven.resolver:maven-resolver-spi:jar:1.4.1:test
[INFO] |  |  |  |  \- org.apache.maven.resolver:maven-resolver-impl:jar:1.4.1:test
[INFO] |  |  |  +- org.apache.maven.resolver:maven-resolver-connector-basic:jar:1.4.1:test
[INFO] |  |  |  +- org.apache.maven.resolver:maven-resolver-transport-wagon:jar:1.4.1:test
[INFO] |  |  |  +- org.apache.maven.wagon:wagon-http:jar:3.3.4:test
[INFO] |  |  |  |  +- org.apache.maven.wagon:wagon-http-shared:jar:3.3.4:test
[INFO] |  |  |  |  |  \- org.jsoup:jsoup:jar:1.12.1:test
[INFO] |  |  |  |  \- org.apache.maven.wagon:wagon-provider-api:jar:3.3.4:test
[INFO] |  |  |  \- org.apache.maven.wagon:wagon-file:jar:3.3.4:test
[INFO] |  |  +- io.quarkus:quarkus-bootstrap-gradle-resolver:jar:1.9.2.Final:test
[INFO] |  |  \- io.smallrye.common:smallrye-common-io:jar:1.4.0:test
[INFO] |  +- org.eclipse.sisu:org.eclipse.sisu.inject:jar:0.3.4:test
[INFO] |  +- io.quarkus:quarkus-test-common:jar:1.9.2.Final:test
[INFO] |  |  +- io.quarkus:quarkus-core-deployment:jar:1.9.2.Final:test
[INFO] |  |  |  +- io.quarkus.gizmo:gizmo:jar:1.0.4.Final:test
[INFO] |  |  |  |  \- org.ow2.asm:asm-util:jar:8.0.1:test
[INFO] |  |  |  |     +- org.ow2.asm:asm-tree:jar:8.0.1:test
[INFO] |  |  |  |     \- org.ow2.asm:asm-analysis:jar:8.0.1:test
[INFO] |  |  |  +- io.quarkus:quarkus-devtools-utilities:jar:1.9.2.Final:test
[INFO] |  |  |  \- io.quarkus:quarkus-builder:jar:1.9.2.Final:test
[INFO] |  |  +- io.quarkus:quarkus-jsonp-deployment:jar:1.9.2.Final:test
[INFO] |  |  |  \- io.quarkus:quarkus-jsonp:jar:1.9.2.Final:test
[INFO] |  |  |     \- org.glassfish:jakarta.json:jar:1.1.6:test
[INFO] |  |  +- org.jboss:jandex:jar:2.2.1.Final:test
[INFO] |  |  \- org.jboss.logging:commons-logging-jboss-logging:jar:1.0.0.Final:test
[INFO] |  +- org.junit.jupiter:junit-jupiter:jar:5.7.0:test
[INFO] |  |  +- org.junit.jupiter:junit-jupiter-api:jar:5.7.0:test
[INFO] |  |  |  +- org.apiguardian:apiguardian-api:jar:1.1.0:test
[INFO] |  |  |  +- org.opentest4j:opentest4j:jar:1.2.0:test
[INFO] |  |  |  \- org.junit.platform:junit-platform-commons:jar:1.7.0:test
[INFO] |  |  +- org.junit.jupiter:junit-jupiter-params:jar:5.7.0:test
[INFO] |  |  \- org.junit.jupiter:junit-jupiter-engine:jar:5.7.0:test
[INFO] |  |     \- org.junit.platform:junit-platform-engine:jar:1.7.0:test
[INFO] |  \- com.thoughtworks.xstream:xstream:jar:1.4.11.1:test
[INFO] |     +- xmlpull:xmlpull:jar:1.1.3.1:test
[INFO] |     \- xpp3:xpp3_min:jar:1.1.4c:test
[INFO] \- io.rest-assured:rest-assured:jar:4.3.0:test
[INFO]    +- org.codehaus.groovy:groovy:jar:3.0.5:test
[INFO]    +- org.codehaus.groovy:groovy-xml:jar:3.0.2:test
[INFO]    +- org.apache.httpcomponents:httpclient:jar:4.5.13:test
[INFO]    |  +- org.apache.httpcomponents:httpcore:jar:4.4.13:test
[INFO]    |  +- commons-logging:commons-logging:jar:1.2:test
[INFO]    |  \- commons-codec:commons-codec:jar:1.14:test
[INFO]    +- org.apache.httpcomponents:httpmime:jar:4.5.13:test
[INFO]    +- org.hamcrest:hamcrest:jar:2.1:test
[INFO]    +- org.ccil.cowan.tagsoup:tagsoup:jar:1.2.1:test
[INFO]    +- io.rest-assured:json-path:jar:4.3.0:test
[INFO]    |  +- org.codehaus.groovy:groovy-json:jar:3.0.5:test
[INFO]    |  \- io.rest-assured:rest-assured-common:jar:4.3.0:test
[INFO]    \- io.rest-assured:xml-path:jar:4.3.0:test
[INFO]       +- org.apache.commons:commons-lang3:jar:3.9:test
[INFO]       +- jakarta.xml.bind:jakarta.xml.bind-api:jar:2.3.2:test
[INFO]       +- com.sun.xml.bind:jaxb-osgi:jar:2.3.0.1:test
[INFO]       \- org.apache.sling:org.apache.sling.javax.activation:jar:0.1.0:test
[INFO]          \- javax.activation:activation:jar:1.1.1:test
