### ISSUE TITLE
Implementing generic interfaces

### ISSUE THREAD

**Issue by floriansiepe** [quarkusio/gizmo#82]
While I was trying to generate Microprofile config [converters](https://download.eclipse.org/microprofile/microprofile-config-1.3/apidocs/org/eclipse/microprofile/config/spi/Converter.html) at build time for user-defined classes, I came into struggle about how to specify the generic class when implementing the interface. I tried to following approaches.

### Implementing via class 
```java
 try (ClassCreator classCreator = ClassCreator.builder()
                    .className(converterClassName)
                    .interfaces(Converter.class)
                    .classOutput(gizmoAdaptor)
                    .build()) {
...
}
```

Unsurprisingly, this wasn't working since the generic wasn't specified anywhere.

### Via signature
After some research, I tried to use the JVM signature directly, which did not lead me to the desired result.
```java
final String s = "Ljava/lang/Object;Lorg/eclipse/microprofile/config/spi/Converter<L" + className.replace(".", "/") + ";>;";

 try (ClassCreator classCreator = ClassCreator.builder()
                    .className(converterClassName)
                    .signature(s)
                    .classOutput(gizmoAdaptor)
                    .build()) {
...
}
```
With `className` as the fully qualified generic class name.

Is there a way the use generics with Gizmo at all? Maybe is there some (internal) documentation about how to use Gizmo?

**Comment by stuartwdouglas** [comment]
What you have above should work, what error were you getting?

**Comment by floriansiepe** [comment]
Sorry for my late reply, I was on holiday. The error message is the following:

```
Exception in thread "main" java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at io.quarkus.bootstrap.runner.QuarkusEntryPoint.doRun(QuarkusEntryPoint.java:48)
        at io.quarkus.bootstrap.runner.QuarkusEntryPoint.main(QuarkusEntryPoint.java:25)
Caused by: java.lang.ExceptionInInitializerError
        at io.quarkus.runner.ApplicationImpl.<clinit>(ApplicationImpl.zig:57)
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
        at java.base/java.lang.Class.newInstance(Class.java:584)
        at io.quarkus.runtime.Quarkus.run(Quarkus.java:65)
        at io.quarkus.runtime.Quarkus.run(Quarkus.java:42)
        at io.quarkus.runtime.Quarkus.run(Quarkus.java:119)
        at io.quarkus.runner.GeneratedMain.main(GeneratedMain.zig:29)
        ... 6 more
Caused by: java.lang.IllegalStateException: SRCFG00012: Can not add converter com.viessmann.vi.config.converter.TestConverter@26275bef that is not parameterized with a type
        at io.smallrye.config.SmallRyeConfig.buildConverters(SmallRyeConfig.java:119)
        at io.smallrye.config.SmallRyeConfig.<init>(SmallRyeConfig.java:67)
        at io.smallrye.config.SmallRyeConfigBuilder.build(SmallRyeConfigBuilder.java:360)
        at io.quarkus.runtime.generated.Config.<clinit>(Config.zig:345)
        ... 16 more
```

`TestConverter` is the class I'm trying to generate with the code above. Quarkus version is currently 1.13.7-Final.

If I look into the generated bytecode (through `mvn clean package -Dquarkus.package.fernflower.enabled=true -DskipTests`) I see the following `TestConverter.java` file:

```
// $FF: synthetic class
public class TestConverter implements Converter {
   private final ObjectMapper om;

   public TestConverter() {
      ObjectMapper var1 = new ObjectMapper();
      this.om = var1;
   }

   public Test convert(String var1) {
      try {
         return this.om.readValue(var1, Test.class);
      } catch (JsonProcessingException var3) {
         throw (Throwable)(new RuntimeException((Throwable)var3));
      }
   }
}
```

**Comment by stuartwdouglas** [comment]
Do you have a reproducer? We use this in Quarkus and it definitely works, the signature that is passed in is just passed directly to ASM.

**Comment by floriansiepe** [comment]
[vi-config.zip](https://github.com/quarkusio/gizmo/files/6783175/vi-config.zip)

Steps to reproduce:
```mvn clean install -DskipTests
cd integration-tests
mvn clean package -Dquarkus.package.fernflower.enabled=true -DskipTests
java -jar target/quarkus-app/quarkus-run.jar
```

Thanks a lot!

**Comment by stuartwdouglas** [comment]
I see this working fine. Make the change you have above to set the signature and the error about not being a generic type is gone.
